import { type GetServerSideProps, type NextPage } from "next";
import Head from "next/head";

import { api } from "~/utils/api";
import { useSession } from "next-auth/react";
import { getServerAuthSession } from "~/server/auth";
import { Profile } from "~/components/Profile";

const Home: NextPage = () => {
  const { data: sessionData } = useSession();
  if (!sessionData) return null;

  return (
    <>
      <Head>
        <title>Budget</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  );
};

export const getServerSideProps: GetServerSideProps = async (context) => {
  const session = await getServerAuthSession(context);
  if (!session) {
    return {
      redirect: {
        destination: "/login",
        permanent: false,
      },
    };
  }
  return {
    props: {
      session,
    },
  };
};

export default Home;
