import { type NextPage } from "next";
import Head from "next/head";

import { api } from "~/utils/api";
import { LoginPanel } from "~/components/LoginPanel";
import { useSession } from "next-auth/react";
import { NavBar } from "~/components/NavBar";

const Home: NextPage = () => {
  const categories = api.category.getAll.useQuery();
  const { data: sessionData } = useSession();
  const user = sessionData?.user;

  return (
    <>
      <Head>
        <title>Budget</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen w-screen flex-col items-center justify-center bg-gray-400">
        <LoginPanel />
        {user && <NavBar />}
      </main>
    </>
  );
};

export default Home;
